// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  blue: string;
  button: string;
  green: string;
  large: string;
  middle: string;
  small: string;
  yellow: string;
}
export const cssExports: CssExports;
export default cssExports;
