// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  Heading: string;
  body1: string;
  title1: string;
  title2: string;
  title3: string;
  title4: string;
  title5: string;
  title6: string;
}
export const cssExports: CssExports;
export default cssExports;
