// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  contentWrap: string;
  description: string;
  logoNotFound: string;
  root: string;
  textNotFound: string;
}
export const cssExports: CssExports;
export default cssExports;
